// <auto-generated />
using System;
using Directory.DataAccesss;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Directory.DataAccess.Migrations
{
    [DbContext(typeof(DirectoryRepositoryDbContext))]
    [Migration("20220604151934_DirectoryMigration")]
    partial class DirectoryMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Directory.Entities.Concrete.ContactInformations.ContactInformationsEntity", b =>
                {
                    b.Property<Guid>("uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("informationContent")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("informationType")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("personuuid")
                        .HasColumnType("uuid");

                    b.HasKey("uuid");

                    b.ToTable("contactInformationsEntities");
                });

            modelBuilder.Entity("Directory.Entities.Concrete.Persons.PersonsEntity", b =>
                {
                    b.Property<Guid>("uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("company")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("firstName")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("lastName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("uuid");

                    b.ToTable("personsEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
